### ISSUE TITLE
Cerberus's SequenceR do not end when running in paralel

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#71] opened 2023-04-30 09:09 UTC
Hi, 

I noticed that when running Cerberus with SequenceR (with 11 bugs in Defects4J) in parallel mode, Cerberus did not quit even after 1 hours. Although all threads have finished with a notification:

<img width="999" alt="Screenshot 2023-04-30 at 7 04 56 pm" src="https://user-images.githubusercontent.com/43113794/235344939-fd52eba3-3ccc-479e-8c10-b7b4df98795e.png">

Status of all tasks in the summary screen still appears as "Validating predictions" or "Running," indicating that the tasks have not yet been completed.

<img width="1275" alt="Screenshot 2023-04-30 at 7 05 26 pm" src="https://user-images.githubusercontent.com/43113794/235345050-50b8ee48-4aa5-423d-a006-69e21849d076.png">

It is quite minor as I still can manually check all thread and close.  However, I really appreciate if you could check this when you have time?

Many thanks.

**Comment by Marti2203** [comment] 2023-04-30 12:10
Hi, was this running in debug mode? I have an idea about it and will make a fix later today

**Comment by thanhlecongg** [comment] 2023-04-30 12:20
I tested multiple times. I think I ran with both debug and normal mode.

**Comment by Marti2203** [comment] 2023-04-30 12:21
Debug mode does not close Cerberus when done. This is intended functionality, the non-debug mode should close but this has to be examined

**Comment by thanhlecongg** [comment] 2023-04-30 12:27
Oh I see. However, the status was still not updated correctly as I observed that it is still "running" or "validating" though the corresponding thread is finished.

**Comment by Marti2203** [comment] 2023-04-30 12:29
Yeah, that is a bug that should be checked out. Thanks for the info!

**Comment by Marti2203** [comment] 2023-05-03 04:59
Hi, I figured out the bug. It was related with the way condition variables were used. It is fixed in dev now. Will close as I am not able to reproduce it anymore

**Closed by Marti2203** 2023-05-03 04:59 UTC
