### ISSUE TITLE
Cerberus do not terminate after running experiments in "-g" mode

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#81] opened 2023-06-01 02:15 UTC
When I try to run Cerberus on "-g" mode, I usually need to close the UI screen by myself (i.e., Ctrl + C). Otherwise, Cerberus will be run forever. To cite an example, please see the following log: 

```
2023-06-01 02:43:29,359 INFO [COMMAND]: cd /scratch/tlecong/APR/cerberus/results ; tar cvzf C1-CC1-sequencer-naturaltransform-Closure-73-9134775a.tar.gz C1-CC1-sequencer-naturaltransform-Closure-73-9134775a ; mv C1-CC1-sequencer-naturaltransform-Closure-73-9134775a.tar.gz /scratch/tlecong/APR/cerberus/results/sequencer

2023-06-01 02:43:29,483 INFO Finished execution for naturaltransform-sequencer-Closure-73-C1-CC1
2023-06-01 02:43:29,484 DEBUG Putting back 8 cores to the job queue
2023-06-01 10:33:44,079 DEBUG The final results are [('naturaltransform-sequencer-Chart-8-C1-CC1', <TaskStatus.SUCCESS: 0>, {'logs': '/scratch/tlecong/APR/cerberus/output/logs/C1-CC1-sequencer-naturaltransform-Chart-8-0198c8f0', 'artifacts': 

....

2023-06-01 10:33:44,133 INFO [OUTPUT]: Run time statistics:
-----------------------
2023-06-01 10:33:44,133 INFO [OUTPUT]: Experiment Count: 59
2023-06-01 10:33:44,134 INFO [OUTPUT]: Cerberus finished successfully after 582.135 minutes
```
My experiments are actually done at 02:43:29. However, Cerberus can only be terminated by myself at 10:33:44. 
Besides, I also observe the container is still running after terminating Cerberus and needs to close manually.

While these issues are minor and do not affect too much, I think it is nice to fix. Thanks.

**Comment by Marti2203** [comment] 2023-06-01 02:21
If you are using the "-g" mode and  debug enabled, Cerberus does not terminate. The container issue has to be examined thugh

**Comment by thanhlecongg** [comment] 2023-06-01 02:26
In my last experiment, I do not use debug model,
```
2023-05-31 18:05:20,123 INFO [CONFIGURATION]: is-debug:false
```

**Comment by Marti2203** [comment] 2023-06-01 02:29
Unfortunately, the UI is tied to the parallel mode. Can you provide with the command you used to try to reproduce it locally?

**Comment by thanhlecongg** [comment] 2023-06-01 02:32
This is my command
```
cerberus repair --tool=sequencer --benchmark=defects4j --bug-index-list=[bug-list-here] --rebuild-all -g
```

**Comment by Marti2203** [comment] 2023-06-01 02:32
Thanks! Will keep you updated

**Comment by Marti2203** [comment] 2023-06-15 02:39
Hi @thanhlecongg , I tried reproducing it today and yesterday but unfortunately I was not able to reproduce it. I will close the issue for now and if you have another situation where it happens, we can reopen it and discuss again.

**Comment by thanhlecongg** [comment] 2023-06-15 02:44
Hi @Marti2203, please try with the big number of bugs in the bug list. I have ran several experiments with the bugs from 10-50 and it always happen. May be you could try with 

```
cerberus repair --tool=recorder --benchmark=defects4j --bug-index-list=1,8,9,10,11,12,13,20,24,75,79,83,103,116,117,122,127,129,131,134,135,137,150,156,167,176,177,186,188,193,606,616,621,624,626,629,633,640,659,661,667,670,676,692,695,697,698,699,706,722,723,724,728,734,735,740,745,747,750,759,761,769,770,776,779,795,797,800,805,809,813,825,828 --rebuild-all -g
```

or

```
cerberus repair --tool=sequencer --benchmark=defects4j --bug-index-list=1,8,9,10,11,12,13,20,24,75,79,83,103,116,117,122,127,129,131,134,135,137,150,156,167,176,177,186,188,193,606,616,621,624,626,629,633,640,659,661,667,670,676,692,695,697,698,699,706,722,723,724,728,734,735,740,745,747,750,759,761,769,770,776,779,795,797,800,805,809,813,825,828 --rebuild-all -g
```
Thanks.

**Comment by Marti2203** [comment] 2023-06-15 02:45
Hi, Will try it now.

**Comment by thanhlecongg** [comment] 2023-06-15 02:46
However, I'm not sure if it happens due to  a specific hardware or not. So if you cannot reproduce, feel free to leave the bugs now. I will try to investigate the root cause of the bug on my device later and let you know if I found any.

**Comment by Marti2203** [comment] 2023-06-15 02:48
I would hypothesize it is some sort of race condition that causes the problem as the parallel mode needs to track the status of all the tasks.

**Comment by thanhlecongg** [comment] 2023-06-15 02:49
Actually, I run Recoder with less 30 bugs and SequenceR with less than 5 bugs, it is still ok. But with big numbers of bugs, e.g. 50., it always happen.

**Comment by thanhlecongg** [comment] 2023-06-16 00:13
Hi @Marti2203 , I have another observations on this bug. The bugs seem to be happen when there are one bugs are not successfully fixed, i.e., Tool returned non-zero status. Hope it help. Thanks.

**Comment by Marti2203** [comment] 2023-06-16 04:46
Hi @thanhlecongg , Thanks, will check it out. This gives me enough ideas how to try reproducing it

**Comment by Marti2203** [comment] 2023-07-10 08:13
Hi @thanhlecongg , I have been running Cerberus for the past week and I have been unable to reproduce this issue, even with the SequenceR examples you had mentioned. Can you reproduce this on your side with the commit 74275387 , which should be the closest to latest today

**Comment by thanhlecongg** [comment] 2023-07-19 01:18
Hi @Marti2203, sorry for a late reply. I will try reproducing it in the commit above and let you know. However, I've been quite busy in recent days so It may have a bit of a delay. Thanks

**Comment by thanhlecongg** [comment] 2023-07-20 08:07
Hi @Marti2203, I am running with Cerberus in a parallel model. However, I face a bug with task_type in both the dev and master branches of Cerberus. Particularly, values.task_type.get() somehow returns an empty string in several functions though it is updated in configurations. 

For example, in this [line](https://github.com/nus-apr/cerberus/blob/master/app/core/configuration.py#L54), the tool_type (is assigned by values.task_type.get() in caller) is empty leading to a failure in import modules. I'm trying to bypass this bug but it will happen in other locations. I'm trying to investigate but cannot understand this bug. 

![Screenshot 2023-07-20 at 6 05 20 pm](https://github.com/nus-apr/cerberus/assets/43113794/b077a022-9c97-4970-9f48-48258e1a25cd)

Therefore, I cannot reproduce the bugs as you requested. Could you help me to resolve the problems first? Thanks. 

P/s: Normal mode still works but parallel mode is buggy.

**Comment by Marti2203** [comment] 2023-07-20 08:09
Hi @thanhlecongg , give me a couple of minutes and I will respond with a fix

**Comment by Marti2203** [comment] 2023-07-20 08:27
Thanks for catching that bug, @thanhlecongg . I have pushed a fix to dev (commit 44a7a188)

**Comment by thanhlecongg** [comment] 2023-07-20 08:37
Thanks for your quick response @Marti2203. The code is running now. I'm reproducing the problem with termination on the current version.

**Comment by thanhlecongg** [comment] 2023-07-20 10:49
Hi @Marti2203, I have completed the command for running 73 bugs with SequenceR. I ran this experiment with Tmux in a 

```
cerberus -task repair --tool=sequencer --benchmark=defects4j --bug-index-list=1,8,9,10,11,12,13,20,24,75,79,83,103,116,117,122,127,129,131,134,135,137,150,156,167,176,177,186,188,193,606,616,621,624,626,629,633,640,659,661,667,670,676,692,695,697,698,699,706,722,723,724,728,734,735,740,745,747,750,759,761,769,770,776,779,795,797,800,805,809,813,825,828 --rebuild-all -g
```
![Screenshot 2023-07-20 at 8 42 44 pm](https://github.com/nus-apr/cerberus/assets/43113794/d373996e-9dcf-4342-8767-a3f3e4f041a4)

After all experiments are finished (Cerberus put back 1 core to the job queue at 18:30 in the following screenshot), the UI is not terminated to move to the next command. To address this, I need to use `Ctrl + C` to close the UI by myself. After the UI is closed, Cerberus continues to run as expected (Calculate and log some summaries about the results at 18:42 in the following screenshot). 

![Screenshot 2023-07-20 at 8 47 35 pm](https://github.com/nus-apr/cerberus/assets/43113794/8d85eb1c-1315-408c-b967-0d14f879040d)

**Comment by Marti2203** [comment] 2023-07-25 01:43
@thanhlecongg I made some more commits - 74965f5f0aa2f contains a strengthened version of the jobs_remaining management logic which ensures mutual exclusion. Can you try again?

**Comment by thanhlecongg** [comment] 2023-07-25 01:56
Yes, I will try to test soon (may be tomorrow). Thanks.

**Comment by Marti2203** [comment] 2023-07-25 01:57
Sure :) no worries

**Comment by Marti2203** [comment] 2023-09-25 03:57
Hi @thanhlecongg, I think this issue has gone stale, and I have updated various things since our talk. I have also had others use the tool on many experiments without issues, so I think the bug should have been resolved. Have you experienced this problem recently?

**Comment by thanhlecongg** [comment] 2023-09-25 11:31
Hi @Marti2203, I have decided to run my experiments on a single model and handle parallel parts by myself so I am not sure about that. However, If you think this issue has been resolved, we should close this issue. If I find any issue, I will report it as soon as possible. Thanks.

**Comment by Marti2203** [comment] 2023-09-25 11:32
Sure, thanks! :)

**Closed by Marti2203** 2023-09-25 11:32 UTC
